/**
 * Base de conhecimento do FAQ — Simulador FAL v0.16.
 * Organizada por seções conforme a Central de Ajuda.
 */

export const FAQ_SECOES = [
  {
    titulo: "Primeiros passos",
    itens: [
      { p: "Para que serve o Simulador FAL?", r: "Ajuda a mensurar como a Reforma Tributária pode afetar as operações da empresa. Para cada operação cadastrada, a ferramenta calcula cinco dimensões: sistema tributário atual; IBS e CBS; transição tributária; preço e margem; caixa e split payment. O objetivo não é apenas informar se haverá aumento ou redução de tributos — também ajuda a identificar necessidade de reajuste de preço, perda de margem, acúmulo de créditos e necessidade adicional de capital de giro." },
      { p: "Quais decisões podem ser apoiadas pelo simulador?", r: "Os resultados podem apoiar: revisão de preços e margens; renegociação de contratos; análise de fornecedores e clientes; planejamento de capital de giro; revisão de cadastros fiscais; parametrização do ERP; análise de crédito presumido; avaliação de split payment; priorização de operações críticas; e preparação do Programa FAL de Transição Tributária." },
      { p: "Qual é a ordem recomendada de uso?", r: "A sequência é: 1) Configuração; 2) Empresas; 3) Transição 2026–2033; 4) Catálogos IBS/CBS; 5) Cenários; 6) Operações; 7) Painel Executivo; 8) revisão das informações de DF-e. Essa ordem reduz o risco de calcular operações com parâmetros incompletos." },
      { p: "Como faço minha primeira simulação?", r: "Siga este fluxo: cadastre a empresa; confira os parâmetros do ano na tela Transição; confira o cClassTrib e, quando aplicável, o cCredPres; crie ou ative um cenário; acesse Operações; clique em Nova operação; preencha os dados econômicos e tributários; salve; clique na linha da operação para abrir o detalhamento; consulte o Painel Executivo para visualizar a consolidação." },
      { p: "Preciso preencher todas as telas antes de usar?", r: "Não necessariamente, mas os parâmetros indispensáveis devem estar disponíveis. Para um cálculo minimamente confiável devem existir: empresa cadastrada; ano correspondente na tabela de transição; cenário ativo; alíquotas atuais da operação; valor bruto; direção; cClassTrib quando houver redução; e informações de crédito quando for entrada." },
      { p: "O simulador calcula o imposto oficial devido?", r: "Não. Ele gera uma estimativa gerencial baseada nas premissas cadastradas. O resultado não deve ser utilizado isoladamente como guia de recolhimento, escrituração ou emissão de documento fiscal." },
      { p: "O simulador substitui uma consultoria tributária?", r: "Não. Ele organiza informações, automatiza cálculos e permite testar hipóteses. Regimes especiais, benefícios fiscais, interpretações legais, contratos e situações específicas precisam de avaliação técnica complementar." },
      { p: "Quem deve utilizar a ferramenta?", r: "Profissionais das áreas tributária, fiscal, contábil, controladoria, financeira, comercial, suprimentos, tecnologia e gestão. A interpretação ideal envolve mais de uma área, porque uma alteração tributária pode gerar efeitos fiscais, financeiros, comerciais e operacionais ao mesmo tempo." },
      { p: "Por que uma mesma operação deve ser simulada em vários anos?", r: "Porque a transição ocorre gradualmente. A mesma venda pode apresentar efeitos diferentes em 2026, 2027, 2029, 2031 e 2033, conforme os fatores dos tributos atuais e as alíquotas de IBS e CBS parametrizadas para cada ano." },
      { p: "Qual é a principal limitação do simulador?", r: "A qualidade da simulação depende da qualidade dos dados. Uma classificação incorreta, uma alíquota desatualizada ou um crédito superestimado pode produzir uma conclusão incorreta mesmo que a fórmula esteja funcionando corretamente." },
    ],
  },
  {
    titulo: "Configuração global",
    itens: [
      { p: "Onde ficam as premissas globais do sistema?", r: "Na página Configuração são definidos: versão do simulador; data-base normativa; cenário ativo; margem-meta; prazo estimado de realização dos créditos; taxa de custo financeiro mensal; e observações gerais." },
      { p: "Como devo preencher a versão do simulador?", r: "Informe a identificação da versão utilizada, por exemplo v0.16. Esse campo não altera as fórmulas — serve para controle, auditoria e rastreabilidade." },
      { p: "O que é a data-base normativa?", r: "É a data até a qual as normas, tabelas e premissas utilizadas foram revisadas. Ela não atualiza automaticamente a legislação. Serve para mostrar qual era a referência normativa da simulação." },
      { p: "Como altero o cenário ativo?", r: "A forma recomendada é acessar a página Cenários, localizar o cenário desejado e clicar em Ativar cenário. Também é possível alterar o nome na Configuração, mas o texto deve ser exatamente igual ao nome de um cenário existente." },
      { p: "O que acontece se eu informar um cenário que não existe?", r: "O sistema tentará localizar o cenário pelo nome. Quando não encontrar, poderá utilizar o primeiro cenário disponível. Por isso, prefira ativar o cenário diretamente pela página Cenários." },
      { p: "Como preencher a margem-meta?", r: "Digite o percentual em pontos percentuais. Exemplo: digite 18 para 18%; digite 12,5 para 12,5%. Não digite 0,18 para representar 18% nessa tela." },
      { p: "Para que serve a margem-meta?", r: "É utilizada no cálculo do preço necessário para preservar a rentabilidade desejada. Na versão atual, a margem configurada globalmente prevalece sobre a margem informada individualmente na operação." },
      { p: "A margem calculada é margem EBITDA?", r: "Não necessariamente. A ferramenta calcula uma margem gerencial da operação, considerando receita ajustada, custo-base e tributos simulados. Ela não contempla automaticamente todas as despesas operacionais necessárias para caracterizar o EBITDA contábil completo." },
      { p: "Como preencher o prazo de realização do crédito?", r: "Informe a quantidade estimada de dias até a compensação, utilização ou ressarcimento do crédito acumulado. Exemplos: 30, 60, 120 ou 180 dias. Quanto maior o prazo, maior tende a ser o custo financeiro estimado." },
      { p: "Como preencher a taxa de custo financeiro?", r: "Digite a taxa mensal em pontos percentuais. Exemplo: digite 1,5 para 1,5% ao mês; digite 2 para 2% ao mês." },
      { p: "Para que serve a taxa financeira?", r: "Ela estima o custo de carregar créditos tributários durante o período em que permanecem sem realização. Esse custo influencia o cálculo de caixa e funding." },
      { p: "Alterar a Configuração recalcula as operações?", r: "Sim. Quando os dados são novamente carregados, o motor utiliza as novas premissas. Uma alteração de margem-meta, prazo do crédito, taxa financeira ou cenário ativo pode modificar diversos resultados simultaneamente." },
      { p: "Preciso clicar em Salvar?", r: "Sim. As alterações somente são persistidas após clicar em Salvar." },
    ],
  },
  {
    titulo: "Cadastro de empresas",
    itens: [
      { p: "Como cadastrar uma empresa?", r: "Acesse Empresas e clique em Nova empresa. Preencha: código interno; razão social; CNPJ ou CPF; grupo empresarial; regime tributário; setor; UF; município; condição de contribuinte do IBS/CBS; condição de produtor rural; condição de cooperativa; ERP; responsável fiscal; e observações." },
      { p: "Como escolher o código da empresa?", r: "Utilize um identificador curto e único. Exemplos: EMP-001; FAL-AUD; FAZENDA-01; MATRIZ; FILIAL-MT. Esse código será utilizado para vincular as operações à empresa." },
      { p: "Existe uma empresa ativa global no sistema?", r: "Não na versão atual. A empresa é selecionada individualmente em cada operação. Na tela Operações é possível filtrar os registros por empresa. O Painel Executivo continua apresentando a base consolidada carregada." },
      { p: "Como analisar apenas uma empresa?", r: "Acesse Operações e utilize o filtro de empresa. O filtro permite revisar as operações daquela empresa, mas ainda não altera os totais do Painel Executivo." },
      { p: "O regime tributário define automaticamente as alíquotas?", r: "Não. Selecionar Lucro Real, Lucro Presumido, Simples Nacional ou Produtor Rural PF não preenche automaticamente PIS, Cofins, ICMS, ISS ou outros tributos. As alíquotas devem ser informadas em cada operação." },
      { p: "As marcações de produtor rural ou cooperativa modificam o cálculo?", r: "Não na versão atual. Essas informações são cadastrais e ajudam na classificação e na revisão técnica, mas ainda não alteram automaticamente as fórmulas." },
      { p: "Posso cadastrar várias empresas de um mesmo grupo?", r: "Sim. Utilize o campo de grupo empresarial. O Painel Executivo, porém, soma as operações sem realizar eliminações entre empresas relacionadas." },
      { p: "Posso excluir uma empresa?", r: "Sim, mas verifique primeiro se existem operações vinculadas ao código. Para preservar o histórico, prefira inativar ou identificar a empresa como não utilizada, em vez de excluir o cadastro." },
    ],
  },
  {
    titulo: "Cadastro de operações",
    itens: [
      { p: "Como cadastrar uma operação?", r: "Acesse Operações e clique em Nova operação. O formulário está dividido em: 1) identificação; 2) valores; 3) classificação fiscal; 4) sistema atual e Reforma Tributária; 5) informações de DF-e. Após preencher, clique em Salvar operação." },
      { p: "O que representa uma operação?", r: "Um evento econômico individual a ser simulado. Exemplos: venda de produto; compra de insumo; prestação de serviço; contratação de serviço; importação; exportação; aquisição de ativo; compra de produtor rural; operação com redução; operação com crédito presumido." },
      { p: "Como preencher o ID da operação?", r: "Utilize um código único e rastreável. Exemplos: OP-0001; VENDA-SOJA-MT-2027; COMPRA-INSUMO-001. Evite repetir o mesmo ID em operações diferentes." },
      { p: "Como escolher a direção da operação?", r: "Selecione Saída para vendas e serviços prestados; Entrada para compras, aquisições e serviços contratados. A direção altera completamente a lógica de débitos, créditos, margem e caixa." },
      { p: "O que acontece se eu cadastrar uma compra como saída?", r: "O sistema poderá calcular débitos quando deveria calcular créditos, produzindo um resultado incorreto. A direção deve ser um dos primeiros campos revisados quando um cálculo parecer incoerente." },
      { p: "Como escolher o tipo da operação?", r: "As opções são: Mercadoria; Serviço; Outro. Para aquisição de ativo, importação ou outra situação não enquadrada, utilize Outro e detalhe a natureza na descrição." },
      { p: "O tipo da operação altera automaticamente a tributação?", r: "Não. O tipo serve para identificação. As alíquotas e classificações ainda precisam ser preenchidas pelo usuário." },
      { p: "Como preencher a descrição?", r: "Utilize uma descrição objetiva que permita reconhecer a operação sem abrir o cadastro. Exemplos: Venda de soja em grão para cliente contribuinte; Compra de fertilizante para produção; Serviço de armazenagem; Aquisição de máquina agrícola." },
      { p: "Qual data devo informar?", r: "Informe a data da operação real ou da operação-modelo. A data funciona como informação cadastral. O parâmetro tributário principal utilizado pelo motor é o campo Ano." },
      { p: "Como preencher o ano?", r: "Informe o ano da transição que deverá ser utilizado no cálculo. Exemplos: 2026, 2027, 2029, 2033. O ano deve existir na página Transição." },
      { p: "Como comparar a mesma operação em anos diferentes?", r: "Cadastre uma cópia para cada ano, mantendo as mesmas premissas econômicas. Exemplo: OP-001-2026, OP-001-2027, OP-001-2029. Isso permite identificar em qual ano a carga, a margem ou o caixa apresentam maior alteração." },
      { p: "Como simular uma venda?", r: "Cadastre como Saída e informe: quantidade; preço; tributos atuais; classificação IBS/CBS; custo-base; percentual de split; e ano da transição." },
      { p: "Como simular uma compra?", r: "Cadastre como Entrada e informe: valor da aquisição; alíquotas atuais; crédito elegível; classificação IBS/CBS; cCredPres quando aplicável; e prazo e custo financeiro globais." },
      { p: "Como simular uma importação?", r: "Utilize o tipo Outro ou Mercadoria, selecione DUIMP como documento e informe manualmente os tributos, classificações e créditos aplicáveis. A versão atual não possui motor aduaneiro automático." },
      { p: "Como simular uma exportação?", r: "Cadastre como Saída, informe a classificação e utilize as alíquotas e reduções correspondentes à hipótese estudada. A escolha exportação não é automática." },
      { p: "Como simular aquisição de ativo imobilizado?", r: "Utilize o tipo Outro, descreva o ativo e cadastre como Entrada. Informe as alíquotas e o percentual de crédito elegível de acordo com a premissa técnica adotada." },
      { p: "Como simular operação com produtor rural?", r: "Cadastre a empresa ou contraparte com a identificação adequada e modele a operação manualmente. A condição de produtor rural não altera automaticamente as fórmulas na versão atual." },
    ],
  },
  {
    titulo: "Valores da operação",
    itens: [
      { p: "Como o valor bruto é calculado?", r: "Quantidade × preço unitário – desconto incondicional + frete + seguro + outras despesas. O resultado não pode ser inferior a zero." },
      { p: "O valor bruto é calculado automaticamente?", r: "Sim. Ao alterar quantidade, preço unitário, desconto, frete, seguro ou outras despesas, o sistema recalcula o valor bruto." },
      { p: "Posso informar diretamente o valor bruto?", r: "Sim. O campo pode ser editado manualmente. Entretanto, uma alteração posterior em quantidade, preço, desconto, frete, seguro ou outras despesas recalculará o valor." },
      { p: "Como simular uma operação sem quantidade definida?", r: "Utilize quantidade 1 e preço unitário igual ao valor total. Exemplo: para uma operação de R$ 100.000, informe quantidade 1 e preço unitário 100.000." },
      { p: "Como preencher descontos?", r: "Informe o valor monetário do desconto, e não o percentual. Exemplo: para desconto de R$ 5.000, informe 5000." },
      { p: "Frete, seguro e outras despesas entram na base?", r: "Sim. Na fórmula atual, esses valores aumentam o valor bruto utilizado na simulação." },
      { p: "Como simular mudança de volume sem duplicar operações?", r: "Utilize o fator de volume na tela Cenários. Observe que, na versão atual, o fator altera a receita utilizada na análise de margem, mas não replica automaticamente todos os tributos da operação." },
    ],
  },
  {
    titulo: "Classificação fiscal",
    itens: [
      { p: "Como preencher NCM e NBS?", r: "Utilize NCM para mercadorias e NBS para serviços, quando aplicável. Na versão atual, esses códigos são informativos e não selecionam automaticamente as alíquotas." },
      { p: "Preciso preencher NCM e NBS ao mesmo tempo?", r: "Normalmente não. Preencha o código compatível com a natureza da operação. Em situações híbridas, avalie a necessidade de separar a operação em mais de um registro." },
      { p: "Como preencher CFOP ou código de serviço?", r: "Informe o código utilizado na operação atual. O campo ajuda na documentação e na revisão, mas não define automaticamente o tratamento tributário." },
      { p: "A UF de origem e destino calculam automaticamente o ICMS?", r: "Não. O usuário deve informar a alíquota de ICMS aplicável. As UFs são armazenadas para identificação e análise." },
      { p: "O município de destino calcula automaticamente o ISS?", r: "Não. O município é registrado como dado da operação, mas a alíquota de ISS precisa ser informada manualmente." },
      { p: "Como escolher o documento fiscal?", r: "Selecione o documento mais relacionado à operação: NF-e, NFC-e, CT-e, NFS-e ou DUIMP. A seleção não altera automaticamente o cálculo." },
      { p: "O regime atual da operação altera as fórmulas?", r: "Não. O regime é uma informação de contexto. As alíquotas atuais devem ser informadas manualmente." },
      { p: "O que é cClassTrib?", r: "É o código de classificação tributária utilizado para identificar o tratamento da operação no IBS e na CBS. Na versão atual, é utilizado principalmente para localizar os percentuais de redução de IBS e CBS." },
      { p: "Como localizar um cClassTrib?", r: "Acesse Catálogos, abra a seção de cClassTrib e pesquise pelo código ou pela descrição. Depois, copie o código para a operação." },
      { p: "O que acontece se eu informar um cClassTrib inexistente?", r: "O sistema não localizará reduções e a classificação aparecerá como pendente. Nessa situação, o IBS e a CBS podem ser calculados pelas alíquotas nominais integrais." },
      { p: "O que é CST IBS/CBS?", r: "É o código de situação tributária associado ao tratamento da operação. Na versão atual, o CST é armazenado para referência, mas não altera diretamente as fórmulas." },
      { p: "O sistema verifica automaticamente se o CST combina com o cClassTrib?", r: "Ainda não de forma completa. A compatibilidade deve ser conferida com os catálogos e com a documentação técnica aplicável." },
    ],
  },
  {
    titulo: "Sistema tributário atual",
    itens: [
      { p: "Quais tributos atuais são calculados?", r: "O módulo contempla: PIS; Cofins; ICMS próprio; FCP; ICMS-ST; ISS; e IPI." },
      { p: "Como preencher as alíquotas atuais?", r: "Digite os percentuais em pontos percentuais. Exemplos: 1,65 para PIS; 7,6 para Cofins; 17 para ICMS; 5 para ISS." },
      { p: "As alíquotas são aplicadas sobre qual base?", r: "Na versão atual, os tributos são aplicados de forma simplificada sobre o valor bruto da operação. Tratamentos especiais de base precisam ser refletidos nas premissas informadas." },
      { p: "Como funciona o cálculo do ICMS-ST?", r: "A ferramenta aplica a MVA sobre o valor bruto, calcula o ICMS sobre a base estimada e deduz o ICMS próprio. A fórmula é gerencial e não substitui cálculos oficiais com pauta, IVA ajustado, redução de base, complemento ou restituição." },
      { p: "Como preencher a MVA-ST?", r: "Digite o percentual em pontos percentuais. Exemplo: digite 40 para MVA de 40%." },
      { p: "Como são calculados os créditos atuais?", r: "Apenas nas operações de Entrada. A base de crédito inclui: PIS; Cofins; ICMS próprio; FCP; e IPI. O resultado é multiplicado pelo percentual de crédito elegível." },
      { p: "ICMS-ST gera crédito no simulador?", r: "Não na fórmula atual." },
      { p: "ISS gera crédito no sistema atual?", r: "Não na fórmula atual." },
      { p: "O que são tributos brutos?", r: "É a soma dos tributos atuais antes da dedução dos créditos." },
      { p: "O que são tributos líquidos?", r: "É o total dos tributos atuais menos os créditos reconhecidos pelo simulador." },
      { p: "O que é carga efetiva atual?", r: "É a relação entre os tributos líquidos e o valor bruto da operação. Exemplo: carga efetiva de 12% significa que os tributos líquidos representam 12% do valor bruto simulado." },
    ],
  },
  {
    titulo: "IBS, CBS e reduções",
    itens: [
      { p: "De onde vêm as alíquotas de IBS e CBS?", r: "As alíquotas são obtidas da página Transição, conforme o ano informado na operação." },
      { p: "Preciso informar IBS e CBS em cada operação?", r: "Não diretamente. O motor busca as alíquotas anuais na tabela de transição e aplica as reduções encontradas no cClassTrib." },
      { p: "O que é alíquota nominal?", r: "É a alíquota cadastrada para o ano, antes das reduções." },
      { p: "O que é alíquota efetiva?", r: "É a alíquota nominal após a aplicação do percentual de redução do cClassTrib. Exemplo: alíquota nominal 20% com redução 60% resulta em alíquota efetiva de 8%." },
      { p: "Como cadastrar uma operação com redução de 60%?", r: "Confira se o cClassTrib correto possui redução de 0,60 no catálogo. Depois, informe esse cClassTrib na operação. Não é necessário reduzir manualmente a alíquota anual." },
      { p: "Como cadastrar uma operação com redução de 30%?", r: "Utilize um cClassTrib cujo percentual de redução esteja parametrizado como 0,30." },
      { p: "Como simular alíquota zero, imunidade ou não incidência?", r: "Utilize o cClassTrib correspondente e confira se a redução ou o tratamento foi corretamente parametrizado. Apenas escrever alíquota zero na descrição não altera o cálculo." },
      { p: "Como são calculados os débitos de IBS e CBS?", r: "Nas operações de Saída, o valor bruto é multiplicado pelas alíquotas efetivas de IBS e CBS." },
      { p: "Como são calculados os créditos de IBS e CBS?", r: "Nas operações de Entrada, o valor bruto é multiplicado pela alíquota efetiva e pelo percentual de crédito elegível." },
      { p: "O que é crédito elegível?", r: "É o percentual do crédito calculado que poderá ser considerado aproveitável na simulação. Exemplo: crédito teórico de R$ 10.000 com crédito elegível de 80% resulta em crédito reconhecido de R$ 8.000." },
      { p: "Como preencher o crédito elegível?", r: "Digite o percentual em pontos percentuais. Exemplo: digite 80 para 80%." },
      { p: "O crédito elegível deve ser preenchido em saídas?", r: "Normalmente não, porque as saídas geram débitos no motor atual." },
      { p: "O IBS/CBS líquido pode ficar negativo?", r: "Não. Quando os créditos superam os débitos, o IBS/CBS líquido fica em zero e o excedente é tratado como crédito acumulado no módulo de caixa." },
      { p: "O que significa classificação pendente?", r: "Significa que o cClassTrib informado não foi localizado no catálogo. O cálculo deve ser revisado antes de ser considerado válido." },
      { p: "O que significa classificação localizada?", r: "Significa que o cClassTrib foi encontrado e suas reduções foram aplicadas. Isso não substitui a confirmação técnica de que o código é adequado à operação." },
      { p: "Como é feita a partilha do IBS entre UF e município?", r: "O motor utiliza as alíquotas de IBS UF e IBS Município cadastradas no ano da transição. Esses valores aparecem no cálculo interno." },
    ],
  },
  {
    titulo: "Crédito presumido",
    itens: [
      { p: "O que é cCredPres?", r: "É o código utilizado para identificar uma hipótese de crédito presumido." },
      { p: "Como consultar um cCredPres?", r: "Acesse Catálogos, abra a seção de créditos presumidos e pesquise pelo código ou pela descrição." },
      { p: "Como cadastrar crédito presumido em uma operação?", r: "Na operação de Entrada: informe o código cCredPres; informe o percentual de crédito presumido de IBS; informe o percentual de crédito presumido de CBS; confira se o código está localizado; e confira se o catálogo indica aplicação ao IBS, à CBS ou a ambos." },
      { p: "O percentual oficial do catálogo é aplicado automaticamente?", r: "Não na versão atual. O campo de percentual oficial ajuda a identificar se a regra está pendente. Os percentuais usados no cálculo são os informados na própria operação." },
      { p: "O que significa status Localizado?", r: "O código foi encontrado no catálogo e não está marcado como pendente." },
      { p: "O que significa status Pendente?", r: "O código existe, mas a regra ou o percentual oficial ainda está identificado como pendente. O crédito presumido não será calculado." },
      { p: "O que significa Não localizado?", r: "O código informado não existe no catálogo. Nenhum crédito presumido será calculado." },
      { p: "O que significa Não informado?", r: "A operação não possui cCredPres preenchido." },
      { p: "Em quais operações o crédito presumido é calculado?", r: "Apenas em operações de Entrada." },
      { p: "Como funciona o método Direto?", r: "O percentual informado é aplicado diretamente sobre o valor da operação." },
      { p: "Como funciona o método Por Fora?", r: "O motor utiliza uma fórmula ajustada: Crédito = valor da operação × percentual ÷ (1 + percentual)." },
      { p: "Como saber qual método está sendo utilizado?", r: "Consulte o campo Método de cálculo no cadastro do cCredPres." },
    ],
  },
  {
    titulo: "Transição 2026–2033",
    itens: [
      { p: "Para que serve a página Transição?", r: "Concentra os parâmetros anuais utilizados pelo motor. Cada ano pode possuir: fator de PIS/Cofins; fator de IPI; fator de ICMS; fator de ISS; alíquota efetiva de IBS; alíquota efetiva de CBS; alíquota do IBS estadual; alíquota do IBS municipal; efeito financeiro; caráter; fonte; e observação." },
      { p: "Como interpretar os fatores dos tributos atuais?", r: "Os fatores são multiplicadores. Exemplos: 1 mantém 100%; 0,90 mantém 90%; 0,60 mantém 60%; 0 elimina o tributo na simulação do ano." },
      { p: "Como preencher as alíquotas na página Transição?", r: "Nessa página, os valores são informados como frações decimais. Exemplos: 0,01 representa 1%; 0,09 representa 9%; 0,18 representa 18%. Essa lógica é diferente da tela de Operações." },
      { p: "O que é efeito financeiro?", r: "É o percentual do IBS e da CBS líquidos que será considerado na carga financeira daquele ano. Exemplos: 0 representa ausência; 1 representa efeito integral; 0,50 representa efeito de 50%." },
      { p: "Como é calculada a carga da transição?", r: "A carga é formada por: PIS/Cofins remanescente; IPI remanescente; ICMS/FCP/ST remanescentes; ISS remanescente; e IBS/CBS com efeito financeiro." },
      { p: "O que é sistema atual remanescente?", r: "É a parcela dos tributos atuais que continua produzindo efeito no ano analisado." },
      { p: "O que é IBS/CBS financeiro?", r: "É o IBS/CBS líquido multiplicado pelo fator de efeito financeiro do ano." },
      { p: "O que é carga total da transição?", r: "É a soma do sistema atual remanescente com o IBS/CBS financeiro." },
      { p: "Como interpretar a diferença versus o sistema atual?", r: "Valor positivo: aumento estimado de carga. Valor negativo: redução estimada de carga. Valor próximo de zero: pouca alteração." },
      { p: "Como interpretar a diferença percentual?", r: "É a diferença em reais dividida pelo valor bruto da operação. Não representa necessariamente o crescimento percentual do imposto em relação ao imposto anterior." },
      { p: "Como analisar a rampa anual?", r: "Cadastre a mesma operação em vários anos e compare: carga total; margem; preço-alvo; split; crédito acumulado; e funding. O objetivo é identificar o ano em que a operação passa a exigir uma ação comercial ou financeira." },
      { p: "Posso alterar os parâmetros anuais?", r: "Sim, mas a alteração afeta todas as operações daquele ano. Registre sempre: fonte; data; responsável; justificativa; e condição oficial ou estimada da premissa." },
      { p: "O que acontece se o ano da operação não existir na tabela?", r: "O motor não encontrará os parâmetros necessários. Isso pode gerar alíquotas e resultados zerados ou incompletos." },
      { p: "Os percentuais legais estão fixos no código?", r: "Não. A tabela é parametrizável. A ferramenta deve ser atualizada sempre que houver alteração normativa ou revisão das premissas." },
    ],
  },
  {
    titulo: "Cenários gerenciais",
    itens: [
      { p: "Para que servem os cenários?", r: "Permitem testar hipóteses comerciais e operacionais sem alterar os dados originais das operações." },
      { p: "Como criar um cenário?", r: "Acesse Cenários, clique em Novo cenário e informe: nome; descrição; fator de volume; fator de preço; fator de custo; e fator de crédito aproveitado." },
      { p: "Como preencher os fatores?", r: "Os fatores são multiplicadores. Exemplos: 1,00 mantém o valor; 1,10 aumenta em 10%; 0,90 reduz em 10%; 1,25 aumenta em 25%." },
      { p: "Como criar um cenário conservador?", r: "Exemplo: fator de volume 0,90; fator de preço 1,00; fator de custo 1,10. Esse cenário simula redução de volume e aumento de custos." },
      { p: "Como criar um cenário otimista?", r: "Exemplo: fator de volume 1,10; fator de preço 1,05; fator de custo 0,98." },
      { p: "Como ativar um cenário?", r: "Clique em Ativar cenário no cartão correspondente. O cenário ativo será utilizado pelo motor de cálculo." },
      { p: "O cenário recalcula todas as operações?", r: "Sim, quando os dados são novamente carregados. Entretanto, os fatores do cenário não afetam todos os módulos da mesma forma." },
      { p: "O fator de volume altera os tributos?", r: "Não na versão atual. Ele altera a receita utilizada no módulo de preço e margem, mas os tributos continuam calculados sobre o valor bruto original." },
      { p: "O fator de preço altera os tributos?", r: "Não na versão atual. Ele altera a receita gerencial da análise de margem." },
      { p: "O fator de custo altera o quê?", r: "Ele multiplica o custo-base utilizado no cálculo de margem." },
      { p: "O fator de crédito aproveitado altera o cálculo?", r: "Não na versão atual. O campo está cadastrado, mas ainda não integra as fórmulas do motor. Para ajustar os créditos, utilize o campo Crédito elegível da operação." },
      { p: "O cenário permite alterar a alíquota do IVA?", r: "Não diretamente. As alíquotas de IBS e CBS são alteradas na página Transição, e não na página Cenários." },
      { p: "A margem-meta é definida no cenário?", r: "Não na versão atual. A margem-meta é definida na Configuração global." },
    ],
  },
  {
    titulo: "Detalhamento do cálculo",
    itens: [
      { p: "Como abrir a memória de cálculo?", r: "Na tela Operações, clique na linha da operação ou na seta localizada ao lado do ID. O painel expandido apresenta cinco módulos." },
      { p: "O que aparece no módulo Sistema atual?", r: "São apresentados: PIS; Cofins; ICMS próprio; FCP; ICMS-ST; ISS; IPI; tributos brutos; créditos atuais; tributos líquidos; e carga efetiva." },
      { p: "O que aparece no módulo IBS/CBS?", r: "São apresentados: alíquotas nominais; alíquotas efetivas; débitos; créditos; crédito presumido; status do crédito presumido; IBS/CBS líquido; carga efetiva; e split retido." },
      { p: "O que aparece no módulo Transição?", r: "São apresentados: tributos atuais remanescentes; IBS/CBS financeiro; carga total da transição; carga efetiva; diferença versus o sistema atual; e diferença percentual." },
      { p: "O que aparece no módulo Preço e margem?", r: "São apresentados: receita ajustada; custo-base; margem atual; margem da transição; margens percentuais; preço necessário para a margem-alvo; diferença de preço; e alerta de margem." },
      { p: "O que aparece no módulo Caixa e split payment?", r: "São apresentados: débito de IBS/CBS; créditos totais; split retido; caixa imediato; crédito acumulado; custo financeiro; caixa após realização; diferença versus o caixa atual; funding; e classificação financeira." },
      { p: "Qual módulo devo analisar primeiro?", r: "Comece por Transição para identificar a alteração de carga. Depois analise: preço e margem; caixa e split; classificação IBS/CBS; e sistema atual." },
      { p: "Como saber se o cálculo precisa ser revisado?", r: "Revise quando houver: classificação pendente; crédito presumido não localizado; preço-alvo incompatível; carga inesperadamente zerada; margem muito negativa; funding muito elevado; ou alíquota efetiva diferente da esperada." },
    ],
  },
  {
    titulo: "Preço e margem",
    itens: [
      { p: "Como é calculada a receita ajustada?", r: "Corresponde a: Valor bruto × fator de volume × fator de preço." },
      { p: "Como é calculado o custo-base?", r: "Nas saídas: Valor bruto × percentual de custo-base × fator de custo. Nas entradas, o valor integral é tratado como custo para fins do motor, mas não há cálculo de margem." },
      { p: "Como preencher o custo-base?", r: "Informe o percentual do valor bruto que representa o custo econômico da operação. Exemplo: venda de R$ 100.000 com custo estimado de R$ 65.000 → custo-base 65." },
      { p: "O custo-base deve incluir despesas administrativas?", r: "Depende da metodologia adotada pela empresa. O campo deve representar de forma consistente o custo necessário para a análise de margem." },
      { p: "Como é calculada a margem atual?", r: "Nas saídas: Receita ajustada – custo-base – tributos líquidos atuais." },
      { p: "Como é calculada a margem da transição?", r: "Nas saídas: Receita ajustada – custo-base – carga total da transição." },
      { p: "Por que as entradas apresentam margem zero?", r: "Porque o módulo foi desenvolvido para analisar margem de operações de saída. Entradas influenciam créditos e caixa, mas não são tratadas como receita." },
      { p: "Como interpretar a margem percentual?", r: "É a margem em reais dividida pela receita ajustada." },
      { p: "O que significa margem abaixo da meta?", r: "Significa que a margem estimada na transição ficou inferior à margem-meta global. O alerta indica necessidade de análise, mas não determina automaticamente que o preço deve ser aumentado." },
      { p: "Como é calculado o preço necessário para a margem-alvo?", r: "O motor utiliza uma metodologia de gross-up híbrido: tributos atuais remanescentes são considerados na estrutura do preço; IBS e CBS financeiros são adicionados conforme sua participação; o custo-base e a margem-meta completam a equação." },
      { p: "O que significa preço bruto para margem-alvo?", r: "É o preço estimado necessário para preservar a margem definida na Configuração." },
      { p: "O preço-alvo é uma recomendação comercial definitiva?", r: "Não. A decisão deve considerar: concorrência; elasticidade; contratos; volume; prazo; relacionamento com o cliente; estratégia de mercado; e possibilidade de absorção parcial." },
      { p: "O que significa diferença de preço?", r: "É o preço-alvo menos o preço atual. Valor positivo: necessidade estimada de aumento. Valor negativo: o preço atual supera o necessário para a margem-meta." },
      { p: "Como utilizar a diferença de preço?", r: "Pode servir como referência para: revisão de tabela; renegociação de contrato; negociação com cliente; análise de mix; avaliação de desconto; e redução de custos." },
      { p: "Por que o preço-alvo aparece zerado?", r: "Isso pode acontecer: em operações de Entrada; quando a margem-meta é excessiva; quando a carga remanescente torna o divisor matemático inválido; ou quando o custo ou os parâmetros estão inconsistentes." },
    ],
  },
  {
    titulo: "Caixa e split payment",
    itens: [
      { p: "O que é split payment?", r: "É a segregação de uma parcela do IBS e da CBS no momento da liquidação financeira. Na prática, parte do valor da venda pode deixar de permanecer disponível no caixa da empresa." },
      { p: "Como preencher o percentual de split?", r: "Digite o percentual em pontos percentuais. Exemplo: digite 100 para simular retenção de 100% do débito de IBS/CBS." },
      { p: "O split é calculado sobre o valor total da venda?", r: "Não. O split é calculado sobre os débitos de IBS e CBS, considerando o percentual informado e o efeito financeiro do ano." },
      { p: "O split é calculado nas entradas?", r: "Normalmente não, porque as entradas não geram débitos de IBS/CBS no motor atual." },
      { p: "Split retido é igual ao imposto líquido?", r: "Não necessariamente. O split considera os débitos. O imposto líquido também considera créditos normais e créditos presumidos." },
      { p: "O split aumenta a carga tributária?", r: "Não necessariamente. Ele pode não alterar o custo tributário, mas pode antecipar a saída financeira e aumentar a necessidade de capital de giro." },
      { p: "O que é caixa imediato?", r: "Nas saídas: Valor bruto – split retido. Nas entradas: saída integral do valor bruto da compra." },
      { p: "O que é crédito acumulado?", r: "É o excedente de créditos de IBS/CBS sobre os débitos da operação." },
      { p: "Como é calculado o custo financeiro do crédito?", r: "Crédito acumulado × taxa mensal × prazo em dias ÷ 30." },
      { p: "O que é caixa após realização?", r: "É o caixa imediato menos o custo financeiro do crédito, mais o crédito acumulado considerado realizado ao final do prazo." },
      { p: "O que significa diferença de caixa versus o sistema atual?", r: "É a comparação entre o caixa estimado no novo modelo e o caixa de referência do sistema atual. Valor positivo: melhora estimada. Valor negativo: pressão adicional de caixa." },
      { p: "O que é funding tributário?", r: "É o valor estimado de recursos adicionais necessário para cobrir uma diferença negativa de caixa." },
      { p: "Funding significa que a empresa precisará contrair empréstimo?", r: "Não obrigatoriamente. A necessidade pode ser coberta por: caixa próprio; revisão de prazos; redução de estoques; antecipação de recebíveis; renegociação com fornecedores; aumento de preço; ou crédito bancário." },
      { p: "Como o funding é classificado?", r: "Baixa: funding igual a zero. Moderada: superior a zero e até 5%. Alta: superior a 5%. Crítica: superior a 10%." },
      { p: "Uma operação lucrativa pode ter funding alto?", r: "Sim. Margem mede resultado econômico. Funding mede necessidade financeira. Uma operação pode ser rentável e, ao mesmo tempo, consumir muito capital de giro." },
      { p: "Um crédito acumulado elevado é sempre positivo?", r: "Não. Ele pode representar valor recuperável, mas também pode gerar: custo financeiro; demora de realização; necessidade documental; risco de glosa; e pressão sobre o caixa." },
    ],
  },
  {
    titulo: "Painel Executivo",
    itens: [
      { p: "Para que serve o Painel Executivo?", r: "Apresenta uma visão consolidada das operações carregadas. São exibidos indicadores de: valor bruto; tributos atuais; carga da transição; IBS/CBS; split; funding; margem; e evolução anual." },
      { p: "O que significa Operações carregadas?", r: "É a quantidade de registros processados pelo motor. Na versão atual, a consulta carrega até 500 operações." },
      { p: "O que significa Valor bruto simulado?", r: "É a soma dos valores brutos das operações de Entrada e Saída. Ele não representa necessariamente faturamento." },
      { p: "O que significa Tributos atuais líquidos?", r: "É a soma dos tributos atuais após os créditos reconhecidos." },
      { p: "O que significa Carga da transição?", r: "É a soma dos tributos atuais remanescentes e do IBS/CBS financeiro." },
      { p: "O que significa IBS/CBS líquido?", r: "É a soma dos valores líquidos de IBS e CBS. Os créditos excedentes não tornam esse indicador negativo." },
      { p: "O que significa Split retido?", r: "É a soma das retenções estimadas nas operações." },
      { p: "O que significa Funding tributário estimado?", r: "É a soma do funding individual das operações. O cálculo não compensa automaticamente a sobra de caixa de uma operação com a necessidade de outra — por isso a visão é conservadora." },
      { p: "O que significa Δ Margem transição?", r: "É a margem total da transição menos a margem total atual. Valor negativo: deterioração de margem. Valor positivo: melhora estimada." },
      { p: "O gráfico de margem apresenta margem em reais?", r: "Não. O gráfico apresenta margem percentual consolidada por ano." },
      { p: "Como o painel agrupa os dados?", r: "As operações são agrupadas pelo ano informado." },
      { p: "O painel respeita o filtro da tela Operações?", r: "Não na versão atual. Os filtros da tela Operações não alteram o Painel Executivo." },
      { p: "Por que entradas e saídas juntas podem distorcer o painel?", r: "Porque o valor bruto consolidado inclui compras e vendas. Para analisar carga sobre faturamento ou margem comercial, é necessário interpretar separadamente as operações de saída." },
      { p: "Por que a margem consolidada pode parecer baixa?", r: "As operações de Entrada possuem margem zero, mas seus valores podem integrar o total usado na consolidação." },
      { p: "Posso comparar anos com bases diferentes?", r: "Sim, mas com cautela. Uma diferença entre anos pode decorrer de: mudança tributária; aumento de volume; mudança de preço; alteração do mix; inclusão de novas operações; ou mudança na proporção entre entradas e saídas." },
    ],
  },
  {
    titulo: "Catálogos fiscais",
    itens: [
      { p: "Para que serve o catálogo de CST?", r: "Registra os códigos de situação tributária e informações associadas. Na versão atual, possui função principalmente cadastral e de apoio à revisão." },
      { p: "Para que serve o catálogo de cClassTrib?", r: "Relaciona: cClassTrib; CST; descrição; redução de IBS; redução de CBS; e status. Os percentuais de redução alimentam diretamente o motor." },
      { p: "Para que serve o catálogo de cCredPres?", r: "Registra: código de crédito presumido; descrição; aplicação ao IBS; aplicação à CBS; percentual oficial; método de cálculo; vigência; fonte; status; e observações." },
      { p: "Como pesquisar um código?", r: "Utilize a busca da página Catálogos e informe: código completo; parte do código; ou palavra da descrição." },
      { p: "Posso editar os catálogos?", r: "Sim. Entretanto, qualquer alteração pode afetar todas as operações relacionadas ao código." },
      { p: "Como preencher as reduções no cClassTrib?", r: "Utilize fração decimal. Exemplos: 0 representa nenhuma redução; 0,30 representa redução de 30%; 0,60 representa redução de 60%; 1 representa redução de 100%." },
      { p: "O que acontece se eu excluir um código?", r: "As operações deixarão de localizar o registro. Isso pode remover reduções ou impedir o cálculo de crédito presumido." },
      { p: "Quem deve manter os catálogos?", r: "Preferencialmente um responsável tributário ou administrador técnico." },
      { p: "Os catálogos são atualizados automaticamente?", r: "Não necessariamente. A governança das tabelas deve incluir revisão periódica, fonte, data e responsável." },
    ],
  },
  {
    titulo: "Informações de DF-e",
    itens: [
      { p: "Para que servem os campos de DF-e?", r: "Registram informações necessárias à preparação cadastral e sistêmica das operações. São exemplos: finalidade; CRT do emitente; ambiente; redução informada; diferimento informado; tributação regular; crédito presumido; compra governamental; e observações." },
      { p: "Os campos de DF-e alteram o cálculo?", r: "Na versão atual, a maioria possui função informativa. Selecionar Sim ou Não não altera automaticamente os débitos ou créditos." },
      { p: "Existe um Validador DF-e completo?", r: "Ainda não. A versão atual permite registrar dados, localizar classificações e identificar alguns status, mas não executa uma validação completa das regras oficiais de NF-e, NFS-e, CT-e ou demais documentos." },
      { p: "O sistema identifica CST incompatível com cClassTrib?", r: "Ainda não de forma completa e automática. A conferência deve ser realizada tecnicamente." },
      { p: "O sistema valida NCM e NBS?", r: "Não de forma homologatória. Os códigos são armazenados, mas não há validação integral com tabelas externas oficiais." },
      { p: "O que significa ambiente Produção ou Homologação?", r: "É a identificação do ambiente relacionado ao documento. Na versão atual, a seleção não altera as fórmulas." },
      { p: "Como utilizar a observação DF-e?", r: "Registre: pendências; justificativas; necessidade de parametrização; regra especial; fonte normativa; responsável pela revisão; e necessidade de teste no ERP." },
      { p: "O simulador substitui o validador oficial?", r: "Não. A emissão e a autorização devem continuar sendo testadas nos ambientes e validadores oficiais." },
    ],
  },
  {
    titulo: "Aplicações práticas",
    itens: [
      { p: "Como identificar as operações que devem ser analisadas primeiro?", r: "Priorize operações com: maior valor bruto; maior aumento de carga; margem abaixo da meta; preço-alvo muito superior ao atual; funding alto ou crítico; crédito acumulado elevado; classificação pendente; ou crédito presumido não localizado." },
      { p: "Como usar o simulador para revisar preços?", r: "Para cada operação de venda: confira o custo-base; confira a margem-meta; analise a carga da transição; observe o preço bruto para margem-alvo; analise a diferença de preço; e avalie a possibilidade comercial de repasse." },
      { p: "Como usar o simulador para revisar contratos?", r: "Identifique contratos com: preço fixo; cláusula tributária genérica; impossibilidade de repasse; prazo longo; margem reduzida; alta exposição a split; ou crédito de lenta realização. Utilize o preço-alvo e o funding como referências para a negociação." },
      { p: "Como usar o simulador para revisar fornecedores?", r: "Compare operações de compra considerando: crédito elegível; crédito presumido; prazo de pagamento; impacto no caixa; risco de crédito acumulado; e custo efetivo." },
      { p: "Como usar o simulador para revisar clientes?", r: "Analise: capacidade de repasse; margem por operação; split retido; prazo de recebimento; necessidade de funding; e diferença de preço." },
      { p: "Como usar o simulador no planejamento de caixa?", r: "Consolide: split retido; créditos acumulados; custo financeiro; funding; e prazo de realização. Depois compare com: fluxo de caixa; saldo disponível; limite bancário; prazo médio de recebimento; e prazo médio de pagamento." },
      { p: "Como usar o simulador na parametrização do ERP?", r: "Mapeie as operações que exigem: novo CST; novo cClassTrib; cCredPres; redução; diferimento; tributação regular; campos de IBS/CBS; partilha do IBS; e tratamento de split payment." },
      { p: "Como usar o simulador no Programa FAL de Transição?", r: "Transforme as pendências identificadas em frentes de trabalho: saneamento cadastral; revisão de contratos; revisão de preços; planejamento financeiro; atualização de ERP; testes de DF-e; governança de créditos; treinamento; e acompanhamento normativo." },
      { p: "Como criar uma operação-modelo?", r: "Escolha uma operação representativa e informe: preço médio; custo médio; alíquotas médias; classificação predominante; crédito elegível; prazo de crédito; e percentual de split. Identifique claramente que se trata de uma premissa gerencial." },
      { p: "Como criar um cenário de estresse?", r: "Exemplo: volume 0,85; preço 0,95; custo 1,15; margem-meta mantida; prazo de crédito ampliado; taxa financeira maior; e split elevado." },
      { p: "Como documentar a simulação?", r: "Registre: versão; data-base normativa; cenário; empresa; operação; fonte dos dados; classificações; premissas; limitações; responsável; e data da revisão." },
    ],
  },
  {
    titulo: "Solução de problemas",
    itens: [
      { p: "Por que todos os tributos aparecem zerados?", r: "Confira: 1) valor bruto; 2) alíquotas atuais; 3) ano; 4) parâmetros da transição; 5) direção; 6) cClassTrib; e 7) efeito financeiro." },
      { p: "Por que IBS e CBS aparecem zerados?", r: "As causas mais comuns são: ano sem parâmetros; alíquotas anuais zeradas; operação de Entrada; redução integral; créditos suficientes para zerar o líquido; ou efeito financeiro zerado." },
      { p: "Por que a classificação está pendente?", r: "O cClassTrib informado não foi localizado no catálogo. Confira espaços, quantidade de dígitos e código utilizado." },
      { p: "Por que o crédito presumido não foi calculado?", r: "Confira: se a direção é Entrada; se o código foi informado; se o código existe; se o percentual oficial não está pendente; se IBS ou CBS são aplicáveis; e se os percentuais foram informados na operação." },
      { p: "Por que o cenário não alterou os tributos?", r: "Porque os fatores de volume e preço afetam a receita gerencial da margem, e não a base tributária da operação." },
      { p: "Por que o fator de crédito do cenário não mudou os créditos?", r: "Porque esse campo ainda não integra as fórmulas. Utilize o crédito elegível da operação." },
      { p: "Por que o preço-alvo ficou muito alto?", r: "Revise: custo-base; margem-meta; carga remanescente; IBS/CBS financeiro; reduções; classificação; cenário; e valor bruto." },
      { p: "Por que o preço-alvo ficou zerado?", r: "Confira: se é uma operação de Entrada; se a margem-meta está muito elevada; se o custo-base está incorreto; ou se a carga torna o cálculo inviável." },
      { p: "Por que o funding ficou muito alto?", r: "As causas mais comuns são: split elevado; crédito acumulado; prazo longo; taxa financeira elevada; ou diferença negativa em relação ao caixa atual." },
      { p: "Por que a margem ficou negativa?", r: "Confira: custo-base; preço; fator de custo; alíquotas; carga da transição; direção; e margem-meta." },
      { p: "Por que o valor bruto mudou sozinho?", r: "O sistema recalcula o valor bruto quando quantidade, preço unitário, desconto, frete, seguro ou outras despesas são alterados." },
      { p: "Por que alterar o regime da empresa não mudou o cálculo?", r: "Porque o regime é cadastral. Ele não seleciona automaticamente as alíquotas." },
      { p: "Por que alterar a UF não mudou o ICMS?", r: "Porque as UFs não alimentam automaticamente uma matriz de alíquotas." },
      { p: "Por que alterar o documento fiscal não mudou o cálculo?", r: "Porque o documento é um campo informativo na versão atual." },
      { p: "Por que o painel não mostra apenas a empresa filtrada?", r: "Porque o filtro de Operações não é aplicado ao Painel Executivo." },
      { p: "Como corrigir um resultado aparentemente incoerente?", r: "Revise nesta ordem: 1) direção; 2) valor bruto; 3) ano; 4) alíquotas atuais; 5) crédito elegível; 6) cClassTrib; 7) reduções; 8) cCredPres; 9) transição; 10) cenário; 11) custo-base; 12) margem-meta; 13) split; 14) prazo; 15) taxa financeira." },
      { p: "As alterações são salvas automaticamente?", r: "Não em todas as telas. Clique em Salvar ou Salvar operação após editar." },
      { p: "A exclusão pode ser desfeita?", r: "A interface solicita confirmação, mas não possui uma função geral de restauração. Faça backup antes de exclusões relevantes." },
    ],
  },
  {
    titulo: "Como interpretar o resultado final",
    itens: [
      { p: "Qual indicador devo analisar primeiro?", r: "Comece pela diferença entre a carga atual e a carga da transição. Depois avalie: margem; preço-alvo; split; crédito acumulado; funding; e classificação fiscal." },
      { p: "Aumento de carga significa automaticamente aumento de preço?", r: "Não. A empresa pode: repassar integralmente; repassar parcialmente; absorver; reduzir custos; alterar o mix; negociar prazos; rever fornecedores; ou descontinuar a operação." },
      { p: "Redução de carga significa ganho líquido?", r: "Não necessariamente. O ganho tributário pode ser reduzido por: maior custo financeiro; split; crédito acumulado; aumento de custos; mudança de preço; ou dificuldades de aproveitamento de crédito." },
      { p: "Margem positiva significa caixa positivo?", r: "Não. Uma operação pode gerar lucro e, ao mesmo tempo, exigir funding." },
      { p: "Funding zero significa ausência de risco?", r: "Não. Ainda podem existir riscos de classificação, preço, crédito, contrato e implementação sistêmica." },
      { p: "Crédito acumulado significa que o dinheiro está disponível?", r: "Não. O crédito pode depender de compensação, ressarcimento, prazo e validação." },
      { p: "Classificação localizada significa que a operação está correta?", r: "Não necessariamente. Significa apenas que o código existe no catálogo e foi encontrado pelo motor." },
      { p: "Qual é a interpretação mais importante do simulador?", r: "O resultado não deve ser reduzido à pergunta 'pagaremos mais ou menos imposto?'. A análise deve responder: o que muda na carga; o que muda na margem; quanto o preço precisaria mudar; quanto poderá ser retido; quanto crédito poderá se acumular; quanto capital de giro poderá ser necessário; quais contratos precisam ser revistos; quais cadastros precisam ser saneados; quais sistemas precisam ser adaptados; e quais operações devem ser priorizadas." },
    ],
  },
];