/**
 * Documentação técnica do Simulador FAL — correlações front-end ↔ back-end.
 * Estrutura consumida pela página ArquiteturaPage.
 * Atualizada em v0.18.
 */

export const ARQUITETURA_RESUMO = {
  stack: "React 18 + Vite + Tailwind CSS + shadcn/ui + TanStack Query v5",
  backend: "Base44 BaaS — entidades (MongoDB), backend functions (Deno/TS), shared modules (JS)",
  auth: "Base44 AuthProvider (OAuth Google + email/senha) — ProtectedRoute em todas as rotas autenticadas",
  realtime: "Subscriptions via base44.entities.<Name>.subscribe() disponível (não utilizado ativamente)",
  versao: "v0.18",
  dataBase: "2026-08-14",
};

export const ENTIDADES = [
  {
    nome: "Grupo",
    arquivo: "base44/entities/Grupo.jsonc",
    pk: "numero",
    descricao: "Grupo econômico/familiar. Raiz do DataHub; cada grupo abre um Workroom.",
    campos: ["numero*", "nome*", "tipo", "ifme_consolidado", "ifme_meta", "status_ifme", "observacao"],
    usadoPor: ["DataHub (CRUD)", "Workroom (load)", "EmpresasPage (filter por grupo)", "processarLoteXML (validação)"],
    sdk: [
      "base44.entities.Grupo.list()",
      "base44.entities.Grupo.get(id)",
      "base44.entities.Grupo.create({...})",
      "base44.entities.Grupo.update(id, {...})",
      "base44.entities.Grupo.delete(id)",
    ],
  },
  {
    nome: "Empresa",
    arquivo: "base44/entities/Empresa.jsonc",
    pk: "id_empresa",
    descricao: "Cadastro mestre de empresas. Vinculada a grupos; alimenta operações e cruzamento de XML.",
    campos: ["id_empresa*", "razao_social*", "grupo", "cnpj_cpf", "regime_atual", "setor", "uf", "municipio", "contribuinte_ibs_cbs", "produtor_rural", "cooperativa", "erp", "responsavel_fiscal", "status", "data_inicio", "observacao"],
    usadoPor: ["EmpresasPage (CRUD)", "useSimuladorData (list)", "OperacoesPage (select)", "processarLoteXML (cruzamento CNPJ)", "confirmarImportacaoXML (validação ativa)"],
    sdk: [
      "base44.entities.Empresa.list()",
      "base44.entities.Empresa.filter({ grupo: numero })",
      "base44.entities.Empresa.create({...})",
      "base44.entities.Empresa.update(id, {...})",
      "base44.entities.Empresa.delete(id)",
    ],
  },
  {
    nome: "Operacao",
    arquivo: "base44/entities/Operacao.jsonc",
    pk: "id_operacao",
    descricao: "Base central das operações. O motor taxEngine calcula 5 módulos a partir destes campos.",
    campos: ["id_operacao*", "empresa_id*", "direcao* (Saida|Entrada)", "valor_bruto*", "data", "ano", "tipo", "descricao", "quantidade", "preco_unitario", "desconto_incondicional", "frete", "seguro", "outras_despesas", "ncm", "nbs", "cfop_servico", "uf_origem", "uf_destino", "municipio_destino", "documento", "regime_atual", "c_class_trib", "cst_ibs_cbs", "pis_pct", "cofins_pct", "icms_pct", "fcp_pct", "mva_st_pct", "iss_pct", "ipi_pct", "credito_elegivel_pct", "split_pct", "c_cred_pres", "credito_presumido_ibs_pct", "credito_presumido_cbs_pct", "grupo_rtc", "custo_base_pct", "margem_meta_pct", "finalidade_dfe", "crt_emitente", "ambiente", "observacao_dfe"],
    usadoPor: ["OperacoesPage (CRUD)", "useSimuladorData (filter + calc)", "Home/consolidarPorAno", "confirmarImportacaoXML (bulkCreate)"],
    sdk: [
      "base44.entities.Operacao.filter({}, '-ano', 500)",
      "base44.entities.Operacao.create({...})",
      "base44.entities.Operacao.update(id, {...})",
      "base44.entities.Operacao.delete(id)",
      "base44.entities.Operacao.bulkCreate([...])",
    ],
  },
  {
    nome: "Cenario",
    arquivo: "base44/entities/Cenario.jsonc",
    pk: "nome",
    descricao: "Cenários gerenciais com fatores de volume, preço, custo e crédito.",
    campos: ["nome*", "descricao", "fator_volume", "fator_preco", "fator_custo", "fator_credito_aproveitado"],
    usadoPor: ["CenariosPage (CRUD)", "useSimuladorData (list + ativo)", "ConfiguracaoPage (cenario_ativo)"],
    sdk: ["base44.entities.Cenario.list()", "base44.entities.Cenario.create({...})", "base44.entities.Cenario.update(id, {...})", "base44.entities.Cenario.delete(id)"],
  },
  {
    nome: "TransicaoAno",
    arquivo: "base44/entities/TransicaoAno.jsonc",
    pk: "ano",
    descricao: "Cronograma paramétrico 2026–2033. Fatores de extinção e alíquotas IBS/CBS por ano.",
    campos: ["ano*", "pis_cofins_fator", "ipi_fator_geral", "icms_fator", "iss_fator", "ibs_efetivo", "ibs_uf_aliquota", "ibs_mun_aliquota", "cbs_efetiva", "efeito_financeiro", "carater", "fonte", "status", "observacao"],
    usadoPor: ["TransicaoPage (CRUD)", "useSimuladorData (list → Map por ano)"],
    sdk: ["base44.entities.TransicaoAno.list()", "base44.entities.TransicaoAno.create({...})", "base44.entities.TransicaoAno.update(id, {...})", "base44.entities.TransicaoAno.delete(id)"],
  },
  {
    nome: "ClassTrib",
    arquivo: "base44/entities/ClassTrib.jsonc",
    pk: "c_class_trib",
    descricao: "Catálogo de classificações tributárias IBS/CBS. Reduções alimentam o motor.",
    campos: ["c_class_trib*", "cst", "descricao_oficial", "grupo_operacional", "pct_reducao_ibs", "pct_reducao_cbs", "tributacao_regular", "credito_presumido", "estorno_credito", "receita_bruta", "dfe_relacionados", "fonte", "publicacao", "status", "observacao"],
    usadoPor: ["CatalogosPage (CRUD)", "useSimuladorData (list → Map)", "processarLoteXML (validação tributária)"],
    sdk: ["base44.entities.ClassTrib.list()", "base44.entities.ClassTrib.filter({})", "base44.entities.ClassTrib.create({...})", "base44.entities.ClassTrib.update(id, {...})"],
  },
  {
    nome: "CstIbsCbs",
    arquivo: "base44/entities/CstIbsCbs.jsonc",
    pk: "cst",
    descricao: "Catálogo oficial de CST IBS/CBS.",
    campos: ["cst*", "descricao_oficial", "exige_tributacao", "reducao_bc", "reducao_aliquota", "transferencia_credito", "diferimento", "monofasica", "credito_presumido_ibs_zfm", "ajuste_competencia", "origem", "publicacao_referencia", "status", "observacao"],
    usadoPor: ["CatalogosPage (CRUD)", "processarLoteXML (validação tributária)"],
    sdk: ["base44.entities.CstIbsCbs.list()", "base44.entities.CstIbsCbs.create({...})", "base44.entities.CstIbsCbs.update(id, {...})"],
  },
  {
    nome: "CredPres",
    arquivo: "base44/entities/CredPres.jsonc",
    pk: "c_cred_pres",
    descricao: "Catálogo oficial de créditos presumidos IBS/CBS.",
    campos: ["c_cred_pres*", "descricao_oficial", "apropria_dfe", "apropria_evento", "deduz_credito_presumido", "ibs_aplicavel", "inicio_ibs", "fim_ibs", "cbs_aplicavel", "inicio_cbs", "fim_cbs", "percentual_oficial", "metodo_calculo", "base_legal_metodo", "fonte", "publicacao", "status", "observacao"],
    usadoPor: ["CatalogosPage (CRUD)", "useSimuladorData (list → Map)", "processarLoteXML (validação tributária)"],
    sdk: ["base44.entities.CredPres.list()", "base44.entities.CredPres.create({...})", "base44.entities.CredPres.update(id, {...})"],
  },
  {
    nome: "Configuracao",
    arquivo: "base44/entities/Configuracao.jsonc",
    pk: "versao_simulador",
    descricao: "Premissas globais do motor. Registro único (primeiro registro é usado).",
    campos: ["versao_simulador*", "data_base_normativa", "cenario_ativo", "margem_meta_pct", "prazo_realizacao_credito_dias", "taxa_custo_financeiro_pct", "observacao"],
    usadoPor: ["ConfiguracaoPage (CRUD)", "useSimuladorData (list → [0])", "CenariosPage (update cenario_ativo)"],
    sdk: ["base44.entities.Configuracao.list()", "base44.entities.Configuracao.create({...})", "base44.entities.Configuracao.update(id, {...})"],
  },
  {
    nome: "Diagnostico",
    arquivo: "base44/entities/Diagnostico.jsonc",
    pk: "grupo_id",
    descricao: "Diagnóstico FAL por grupo. Pipeline de 5 etapas.",
    campos: ["grupo_id*", "nome", "etapa_atual", "status (rascunho|em_progresso|em_validacao|finalizado)", "data_criacao", "observacao"],
    usadoPor: ["Workroom (load)", "WorkroomOverview"],
    sdk: ["base44.entities.Diagnostico.filter({ grupo_id })"],
  },
  {
    nome: "ImportacaoXMLLote",
    arquivo: "base44/entities/ImportacaoXMLLote.jsonc",
    pk: "idempotency_key",
    descricao: "Lote de importação de XML. Controla idempotência e status do processamento assíncrono.",
    campos: ["grupo_id*", "idempotency_key*", "status (RECEBIDO→PROCESSANDO→AGUARDANDO_CONFIRMACAO|PROCESSADO|PROCESSADO_COM_FALHAS|FALHOU)", "total_arquivos", "arquivos_validos", "arquivos_invalidos", "total_itens", "itens_importaveis", "itens_importaveis_com_alerta", "itens_bloqueados", "itens_duplicados", "itens_cancelados", "itens_confirmados", "versao_regras", "processado_em", "observacao"],
    usadoPor: ["useImportacaoXML (create + poll)", "processarLoteXML (create + update)", "confirmarImportacaoXML (update)"],
    sdk: [
      "base44.entities.ImportacaoXMLLote.create({...})",
      "base44.entities.ImportacaoXMLLote.get(id)  // poll",
      "base44.entities.ImportacaoXMLLote.filter({ grupo_id, idempotency_key })  // idempotência",
      "base44.entities.ImportacaoXMLLote.update(id, {...})",
    ],
  },
  {
    nome: "ImportacaoXMLArquivo",
    arquivo: "base44/entities/ImportacaoXMLArquivo.jsonc",
    pk: "id (auto)",
    descricao: "Arquivo XML dentro de um lote. Um por arquivo enviado.",
    campos: ["lote_id*", "grupo_id*", "nome_original*", "storage_key", "hash_sha256", "tamanho_bytes", "tipo_xml (NFE_PROC|NFE|EVENTO_*|XML_DESCONHECIDO)", "situacao_fiscal (AUTORIZADO|CANCELADO|DUPLICADO_HASH|DUPLICADO_CHAVE|...)", "status_tecnico (PENDENTE|PROCESSANDO|CONCLUIDO|FALHOU)", "chave_nfe", "numero_nf", "serie", "data_emissao", "cstat", "xmotivo", "ambiente", "qtd_itens", "motivo_duplicidade", "erro_processamento", "processado_em"],
    usadoPor: ["processarLoteXML (bulkCreate + bulkUpdate)", "useImportacaoXML (filter por lote)", "ArquivosLog (display)"],
    sdk: [
      "base44.entities.ImportacaoXMLArquivo.bulkCreate([...])",
      "base44.entities.ImportacaoXMLArquivo.bulkUpdate([{id, ...}])",
      "base44.entities.ImportacaoXMLArquivo.filter({ lote_id })",
    ],
  },
  {
    nome: "ImportacaoXMLItem",
    arquivo: "base44/entities/ImportacaoXMLItem.jsonc",
    pk: "id (auto)",
    descricao: "Item extraído de NF-e, por perspectiva (EMITENTE/DESTINATARIO). Inclui 4 camadas de validação JSON.",
    campos: ["lote_id*", "grupo_id*", "chave_nfe*", "numero_item*", "arquivo_id", "empresa_id", "perspectiva (EMITENTE|DESTINATARIO)", "direcao (Entrada|Saida)", "tipo_relacionamento (TERCEIRO|INTERCOMPANY|TRANSFERENCIA_INTERNA)", "status_mapeamento", "resultado_final (IMPORTAVEL|IMPORTAVEL_COM_ALERTA|BLOQUEADO|CANCELADO|DUPLICADO)", "validacao_documental_json", "validacao_cadastral_json", "validacao_tributaria_json", "validacao_operacional_json", "snapshot_versoes_json", "vinculo_item_id", "confirmado_em", "operacao_id", "+ campos tributários original/normalizado por alíquota"],
    usadoPor: ["processarLoteXML (bulkCreate)", "useImportacaoXML (filter por lote)", "StagingTable (display)", "ValidacaoDrawer (display)", "confirmarImportacaoXML (filter + bulkUpdate)"],
    sdk: [
      "base44.entities.ImportacaoXMLItem.bulkCreate([...])",
      "base44.entities.ImportacaoXMLItem.bulkUpdate([{id, ...}])",
      "base44.entities.ImportacaoXMLItem.filter({ lote_id })",
      "base44.entities.ImportacaoXMLItem.filter({ grupo_id, chave_nfe })  // cancelamento",
    ],
  },
  {
    nome: "HistoricoXML",
    arquivo: "base44/entities/HistoricoXML.jsonc",
    pk: "id (auto)",
    descricao: "Trilha de auditoria de itens importados. Previne reimportação da mesma perspectiva.",
    campos: ["grupo_id*", "chave_nfe*", "numero_item*", "perspectiva* (EMITENTE|DESTINATARIO)", "empresa_id", "operacao_id", "lote_id", "importado_em"],
    usadoPor: ["processarLoteXML (filter → Set para dedup)", "confirmarImportacaoXML (filter + bulkCreate)"],
    sdk: [
      "base44.entities.HistoricoXML.filter({ grupo_id })  // dedup em memória",
      "base44.entities.HistoricoXML.bulkCreate([...])",
    ],
  },
];

export const BACKEND_FUNCTIONS = [
  {
    nome: "processarLoteXML",
    arquivo: "base44/functions/processarLoteXML/entry.ts",
    descricao: "Recebe lote de XMLs, cria registros, processa assíncrono (waitUntil) com download+parse paralelo, 4 camadas de validação e bulkCreate de itens.",
    input: {
      grupo_id: "string (obrigatório)",
      idempotency_key: "string UUID (obrigatório)",
      arquivos: "Array<{ nome: string, file_url: string, tamanho: number }> (obrigatório, máx 5000)",
    },
    output: {
      success: "{ lote_id: string, status: 'RECEBIDO' }",
      error: "{ error: string } (400|404|500)",
    },
    fluxo: [
      "1. Auth (base44.auth.me) — rejeita se não logado",
      "2. Validação de payload (grupo_id, idempotency_key, arquivos não vazios, máx 5000)",
      "3. Valida grupo existe (Grupo.get)",
      "4. Idempotência: filter ImportacaoXMLLote por (grupo_id, idempotency_key) — retorna existente se encontrado",
      "5. Cria lote (status RECEBIDO)",
      "6. bulkCreate ImportacaoXMLArquivo (PENDENTE) em batches de 500",
      "7. waitUntil(processarLote) — processamento assíncrono",
      "8. Retorna imediatamente { lote_id, status: RECEBIDO }",
    ],
    processamentoAssincrono: [
      "A. Update lote → PROCESSANDO",
      "B. Load: Empresas (filter por grupo), CstIbsCbs, ClassTrib, CredPres, HistoricoXML (filter por grupo)",
      "C. Loop em batches de 50 arquivos:",
      "  C1. Promise.all: fetch + sha256 + parseXml + identificarTipoXml (paralelo)",
      "  C2. Sequencial: dedup hash → dedup chave → eventos → NFE → preparar itens em memória",
      "  C3. Flush: bulkUpdate arquivos (500) + bulkCreate itens (500)",
      "D. Flush remainder",
      "E. Update lote → status final + contadores",
    ],
    validacoes: [
      "Documental: XML bem-formado, tipo reconhecido, chave válida (módulo 11), protocolo, cStat, ambiente, cancelamento, data emissão",
      "Cadastral: empresa localizada, CNPJ cruzado, NCM/NBS, CFOP, UFs, descrição, valor bruto",
      "Tributária: CST no catálogo, cClassTrib no catálogo, cCredPres no catálogo, grupo RTC",
      "Operacional: perspectiva duplicada no histórico, quantidade negativa",
    ],
    shared: ["xmlUtils.js (normalizeCnpj, parsePercentage, originalValue, validateAccessKey, sha256, check, STATUS)", "xmlParser.js (parseXml, getFirst, getAll, getText, getAttr, identificarTipoXml, MAX_ITENS)"],
  },
  {
    nome: "confirmarImportacaoXML",
    arquivo: "base44/functions/confirmarImportacaoXML/entry.ts",
    descricao: "Confirma importação de itens selecionados: cria Operações, HistóricoXML e marca itens como confirmados. Otimizado com bulk operations.",
    input: {
      lote_id: "string (obrigatório)",
      perspectivas_ids: "string[] (obrigatório, IDs de ImportacaoXMLItem)",
    },
    output: {
      success: "{ lote_id, confirmados: number, erros: number, resultados: Array<{id, sucesso, operacao_id?, erro?}>, status: 'CONCLUIDO'|'CONCLUIDO_COM_ERROS' }",
      error: "{ error: string } (400|404|500)",
    },
    fluxo: [
      "1. Auth + validação de payload",
      "2. Carrega lote (ImportacaoXMLLote.get)",
      "3. Batch load: filter ImportacaoXMLItem por lote_id (1 query)",
      "4. Filtra itens selecionados e elegíveis (IMPORTAVEL | IMPORTAVEL_COM_ALERTA)",
      "5. Batch load: Empresas únicas (Promise.all gets)",
      "6. Batch load: HistoricoXML do grupo (1 query → Set para dedup em memória)",
      "7. Processamento em memória: valida duplicidade + empresa ativa → prepara Operação data",
      "8. bulkCreate Operacao (batches de 500, com fallback individual)",
      "9. bulkCreate HistoricoXML (batches de 500, com fallback)",
      "10. bulkUpdate ImportacaoXMLItem (batches de 500, com fallback)",
      "11. Update lote.itens_confirmados",
    ],
    mapeamento: "ImportacaoXMLItem → Operacao: id_operacao = IMP-{chave[25:34]}-{numero_item}-{perspectiva[0:3]}, empresa_id = empresa.id_empresa, + 30+ campos tributários normalizados",
  },
];

export const FRONTEND_PAGES = [
  { rota: "/", componente: "DataHub", arquivo: "src/pages/DataHub.jsx", entidades: ["Grupo (CRUD)"], descricao: "Hub de grupos econômicos. CRUD completo com Dialog." },
  { rota: "/cockpit", componente: "Home", arquivo: "src/pages/Home.jsx", entidades: ["Grupo (list)", "Empresa (filter por grupo)"], shared: ["components/painel/PainelExecutivoView"], descricao: "Wrapper fino do Painel Executivo standalone — seletor de Grupo e, dentro dele, de Empresa. Todo o cálculo/KPIs vive em PainelExecutivoView, reaproveitado também dentro do workspace de cada empresa." },
  { rota: "/workroom/:id", componente: "Workroom", arquivo: "src/pages/Workroom.jsx", entidades: ["Grupo (get)"], descricao: "Container do Workroom — PageHeader (breadcrumb + voltar) só na visão geral; cada rota filha (Empresas, Operações, Importação XML, workspace de empresa) tem o próprio cabeçalho." },
  { rota: "/workroom/:id (index)", componente: "WorkroomOverview", arquivo: "src/pages/WorkroomOverview.jsx", entidades: ["Empresa (filter por grupo)"], descricao: "Grade de empresas do grupo (EmpresaCard) como conteúdo principal — abrir uma leva ao workspace dela. Bases técnicas (Cenários/Transição/Catálogos) ficam num bloco secundário, compartilhado entre grupos." },
  { rota: "/workroom/:id/empresas", componente: "EmpresasPage", arquivo: "src/pages/EmpresasPage.jsx", entidades: ["Empresa (CRUD filter por grupo)", "Grupo (get)"], descricao: "Cadastro completo de empresas do grupo — clicar numa linha abre o workspace dela." },
  { rota: "/workroom/:id/empresas/:empresaId", componente: "EmpresaWorkroom", arquivo: "src/pages/EmpresaWorkroom.jsx", entidades: ["Empresa (get)", "Grupo (get)"], descricao: "Workspace de uma única empresa — PageHeader (breadcrumb DataHub > Grupo > Empresa) + abas Painel/Operações/Importação XML, todas travadas nesta empresa." },
  { rota: "/workroom/:id/empresas/:empresaId (index)", componente: "EmpresaPainel", arquivo: "src/pages/EmpresaPainel.jsx", shared: ["components/painel/PainelExecutivoView"], descricao: "Painel Executivo desta empresa — mesmo componente do /cockpit, escopado por empresaId, sem seletores (contexto já vem da URL)." },
  { rota: "/workroom/:id/operacoes | /workroom/:id/empresas/:empresaId/operacoes", componente: "OperacoesPage", arquivo: "src/pages/OperacoesPage.jsx", entidades: ["Operacao (CRUD)", "Empresa (read)", "TransicaoAno (read)", "ClassTrib (read)", "Cenario (read)", "Configuracao (read)", "CredPres (read)"], hooks: ["useSimuladorData"], shared: ["taxEngine.calcOperacao"], componentes: ["OperacaoForm", "OperacaoCalcDetail"], descricao: "Tabela de operações. Reaproveitada em dois níveis: grupo inteiro (filtro manual de empresa) ou travada numa empresa via useOutletContext() quando aninhada em EmpresaWorkroom." },
  { rota: "/workroom/:id/importacao-xml | /workroom/:id/empresas/:empresaId/importacao-xml", componente: "ImportacaoXMLPage", arquivo: "src/pages/ImportacaoXMLPage.jsx", entidades: ["ImportacaoXMLLote (read)", "ImportacaoXMLArquivo (read)", "ImportacaoXMLItem (read)", "Empresa (filter por grupo, p/ nomes)"], hooks: ["useImportacaoXML"], backend: ["processarLoteXML", "confirmarImportacaoXML"], integrations: ["Core.UploadFile"], componentes: ["DropzoneXML", "ArquivosLog", "StagingTable", "ValidacaoDrawer"], descricao: "Upload de XML — o lote continua sendo do grupo (uma nota pode envolver duas empresas do mesmo grupo), mas dentro do workspace de uma empresa a tela filtra por padrão só os itens dela, com toggle para revelar transferência interna." },
  { rota: "/transicao", componente: "TransicaoPage", arquivo: "src/pages/TransicaoPage.jsx", entidades: ["TransicaoAno (CRUD)"], descricao: "CRUD do cronograma de transição 2026–2033." },
  { rota: "/catalogos", componente: "CatalogosPage", arquivo: "src/pages/CatalogosPage.jsx", entidades: ["CstIbsCbs (CRUD)", "ClassTrib (CRUD)", "CredPres (CRUD)"], descricao: "Catálogos fiscais com tabs e busca." },
  { rota: "/configuracao", componente: "ConfiguracaoPage", arquivo: "src/pages/ConfiguracaoPage.jsx", entidades: ["Configuracao (CRUD singleton)"], descricao: "Premissas globais do motor." },
  { rota: "/manual", componente: "ManualPage", arquivo: "src/pages/ManualPage.jsx", descricao: "FAQ + fluxograma manual. Conteúdo estático em faqData.js." },
];

export const HOOKS = [
  {
    nome: "useSimuladorData",
    arquivo: "src/hooks/useSimuladorData.js",
    descricao: "Carrega todas as entidades base e calcula operações com o motor taxEngine.",
    queries: [
      { key: '["operacoes"]', fn: "base44.entities.Operacao.filter({}, '-ano', 500)" },
      { key: '["transicao"]', fn: "base44.entities.TransicaoAno.list()" },
      { key: '["classTrib"]', fn: "base44.entities.ClassTrib.list()" },
      { key: '["cenario"]', fn: "base44.entities.Cenario.list()" },
      { key: '["config"]', fn: "base44.entities.Configuracao.list()" },
      { key: '["empresas"]', fn: "base44.entities.Empresa.list()" },
      { key: '["credPres"]', fn: "base44.entities.CredPres.list()" },
    ],
    transformacoes: [
      "config = configQ.data?.[0] || {}",
      "cenarioAtivo = cenarios.find(c => c.nome === config.cenario_ativo) || cenarios[0]",
      "transicaoMap = Map(transicao.map(t => [t.ano, t]))",
      "classTribMap = Map(classTrib.map(c => [c.c_class_trib, c]))",
      "credPresMap = Map(credPres.map(c => [c.c_cred_pres, c]))",
      "operacoesCalculadas = operacoes.map(op => calcOperacao(op, anoParams, classTrib, cenarioAtivo, config, credPresMap))",
    ],
    retorna: ["isLoading", "operacoes", "operacoesCalculadas", "transicao", "classTrib", "cenarios", "cenarioAtivo", "config", "empresas", "credPres", "refetch()"],
    shared: ["taxEngine.calcOperacao", "taxEngine.consolidarPorAno"],
  },
  {
    nome: "useImportacaoXML",
    arquivo: "src/hooks/useImportacaoXML.js",
    descricao: "Gestão completa do ciclo de importação de XML: upload, processamento, poll e confirmação.",
    estado: ["selectedFiles", "uploading", "uploadProgress {current, total}", "loteId", "error"],
    queries: [
      { key: '["lote-xml", loteId]', fn: "base44.entities.ImportacaoXMLLote.get(loteId)", poll: "2s enquanto RECEBIDO|PROCESSANDO" },
      { key: '["arquivos-xml", loteId]', fn: "base44.entities.ImportacaoXMLArquivo.filter({ lote_id })", enabled: "lote processado" },
      { key: '["itens-xml", loteId]', fn: "base44.entities.ImportacaoXMLItem.filter({ lote_id })", enabled: "lote processado" },
    ],
    acoes: [
      "addFiles(files) — valida .xml + 2MB + máx 5000",
      "enviarProcessamento() — UploadFile paralelo (concurrency 10) → processarLoteXML",
      "confirmarImportacao(ids) — invoke confirmarImportacaoXML",
    ],
    integrations: ["Core.UploadFile (paralelo, 10 concurrent)"],
    backend: ["processarLoteXML", "confirmarImportacaoXML"],
    retorna: ["selectedFiles", "addFiles", "removeFile", "clearFiles", "uploading", "uploadProgress", "enviarProcessamento", "error", "loteId", "lote", "arquivos", "itens", "confirmarImportacao"],
  },
];

export const SHARED_MODULES = [
  {
    nome: "taxEngine.js",
    arquivo: "base44/shared/taxEngine.js",
    descricao: "Motor de cálculo tributário. 5 módulos: sistema atual, IBS/CBS, transição, preço/margem, caixa/split.",
    funcoes: [
      { nome: "calcOperacao(op, anoParams, classTrib, cenarioAtivo, config, credPresMap)", retorna: "{ sistemaAtual, ibsCbs, transicao, precoMargem, caixa }", descricao: "Calcula uma operação completa." },
      { nome: "consolidarPorAno(operacoesCalculadas)", retorna: "Array<{ ano, valorBruto, tributosAtuaisLiquidos, cargaTransicao, ibsCbsLiquido, splitRetido, funding, margemAtual, margemTransicao }>", descricao: "Agrega operações por ano para o painel executivo." },
    ],
    usadoPor: ["useSimuladorData", "Home"],
  },
  {
    nome: "xmlUtils.js",
    arquivo: "base44/shared/xmlUtils.js",
    descricao: "Utilitários para processamento de XML de NF-e.",
    funcoes: [
      { nome: "normalizeCnpj(cnpj)", retorna: "string (14 dígitos)", descricao: "Normaliza CNPJ removendo máscara." },
      { nome: "parsePercentage(value)", retorna: "number [0,1]", descricao: "Converte string/number para fração decimal." },
      { nome: "originalValue(value)", retorna: "string", descricao: "Preserva valor original do XML para auditoria." },
      { nome: "validateAccessKey(chave, { cnpjEmitente, modelo, serie, numero })", retorna: "{ valido, codigo, mensagem }", descricao: "Valida chave de 44 dígitos (módulo 11) + coerência." },
      { nome: "sha256(bytes)", retorna: "string (hex)", descricao: "Hash SHA-256 para deduplicação." },
      { nome: "check(codigo, status, mensagem, bloqueante, campo)", retorna: "{ codigo, status, mensagem, bloqueante, campo }", descricao: "Cria objeto de check de validação." },
    ],
    constantes: ["VERSAO_REGRAS = 'v0.18'", "STATUS = { CONFORME, NAO_CONFORME, ALERTA, PENDENTE, NAO_APLICAVEL }", "UF_CODIGOS = { ... }"],
    usadoPor: ["processarLoteXML"],
  },
  {
    nome: "xmlParser.js",
    arquivo: "base44/shared/xmlParser.js",
    descricao: "Parser XML seguro usando @xmldom/xmldom. Bloqueia DTD/entidades externas.",
    funcoes: [
      { nome: "parseXml(content)", retorna: "Document", descricao: "Parse com DOMParser seguro (max 2MB, profundidade 50)." },
      { nome: "getFirst(parent, tagName)", retorna: "Element | null", descricao: "Busca primeiro filho por localName (case-insensitive)." },
      { nome: "getAll(parent, tagName)", retorna: "Element[]", descricao: "Busca todos os filhos por localName." },
      { nome: "getText(parent, tagName)", retorna: "string", descricao: "Extrai texto de um filho." },
      { nome: "getAttr(el, attrName)", retorna: "string", descricao: "Extrai atributo de um elemento." },
      { nome: "identificarTipoXml(doc)", retorna: "'NFE_PROC'|'NFE'|'EVENTO_CANCELAMENTO'|'EVENTO_CARTA_CORRECAO'|'EVENTO_OUTRO'|'XML_DESCONHECIDO'", descricao: "Classifica o tipo de documento XML." },
    ],
    constantes: ["MAX_TAMANHO_XML = 2MB", "MAX_ITENS = 500 (por NF-e)", "MAX_DEPTH = 50"],
    usadoPor: ["processarLoteXML"],
  },
];

export const INTEGRATIONS = [
  { nome: "Core.UploadFile", usadoPor: ["useImportacaoXML"], descricao: "Upload de arquivo para storage. Retorna { file_url }. Usado em paralelo (10 concurrent) para upload de XML." },
  { nome: "Core.InvokeLLM", usadoPor: ["(disponível, não utilizado ativamente)"], descricao: "LLM para análise de dados. Disponível para futuras features de análise automática." },
  { nome: "Core.ExtractDataFromUploadedFile", usadoPor: ["(disponível)"], descricao: "Extração estruturada de CSV/Excel/JSON/PDF." },
  { nome: "Core.GenerateImage", usadoPor: ["(disponível)"], descricao: "Geração de imagens via IA." },
  { nome: "Core.SendEmail", usadoPor: ["(disponível)"], descricao: "Envio de email para usuários registrados." },
];

export const ORIENTACOES = {
  arquivo: "src/lib/orientacoes.js",
  descricao: "Dicionário central de orientações técnicas. Consumido pelo componente InfoTooltip.",
  consumo: '<InfoTooltip pagina="config" chave="margem_meta" />',
  paginas: ["config", "datahub", "empresas", "operacoes", "operacao_form", "cenarios", "transicao", "catalogos", "home", "workroom", "manual", "importacao"],
};

export const COMPONENTES_AUXILIARES = [
  { nome: "InfoTooltip", arquivo: "src/components/InfoTooltip.jsx", descricao: "Ícone ℹ com Popover (Radix Portal). Busca orientação no dicionário ou usa texto literal." },
  { nome: "PipelineStepper", arquivo: "src/components/PipelineStepper.jsx", descricao: "Navegação visual de 5 etapas do pipeline do Workroom." },
  { nome: "KpiCard", arquivo: "src/components/KpiCard.jsx", descricao: "Card de KPI com label, valor e subtexto." },
  { nome: "GrupoCard", arquivo: "src/components/GrupoCard.jsx", descricao: "Card de grupo no DataHub com ações editar/excluir." },
  { nome: "Layout", arquivo: "src/components/Layout.jsx", descricao: "Layout principal com sidebar/topbar. Envolve todas as rotas via <Outlet />." },
  { nome: "ProtectedRoute", arquivo: "src/components/ProtectedRoute.jsx", descricao: "Guard de autenticação. Renderiza <Outlet /> se autenticado, senão redirect." },
  { nome: "ScrollToTop", arquivo: "src/components/ScrollToTop.jsx", descricao: "Scroll para topo em mudança de rota." },
  { nome: "ThemeProvider", arquivo: "src/components/ThemeProvider.jsx", descricao: "Provider de tema (light/dark) via next-themes." },
  { nome: "OperacaoForm", arquivo: "src/components/operacoes/OperacaoForm.jsx", descricao: "Formulário de operação com 5 seções + InfoTooltip em cada campo." },
  { nome: "OperacaoCalcDetail", arquivo: "src/components/operacoes/OperacaoCalcDetail.jsx", descricao: "Detalhamento dos 5 módulos de cálculo de uma operação." },
  { nome: "DropzoneXML", arquivo: "src/components/importacao/DropzoneXML.jsx", descricao: "Drag-and-drop de XML com barra de progresso de upload." },
  { nome: "ArquivosLog", arquivo: "src/components/importacao/ArquivosLog.jsx", descricao: "Tabela de logs de arquivos processados." },
  { nome: "StagingTable", arquivo: "src/components/importacao/StagingTable.jsx", descricao: "Tabela de itens staging com seleção e agrupamento intercompany." },
  { nome: "ValidacaoDrawer", arquivo: "src/components/importacao/ValidacaoDrawer.jsx", descricao: "Drawer com detalhes das 4 camadas de validação por item." },
];